"""List of items in Ori and the Will of the Wisps."""

from BaseClasses import ItemClassification

base_id = 3154879345  # Arbitrary value

item_table = [
    # Skills, 23 in total
    {"name": "Sword", "count": 1, "classification": ItemClassification.progression},
    {"name": "DoubleJump", "count": 1, "classification": ItemClassification.progression},
    {"name": "Regenerate", "count": 1, "classification": ItemClassification.progression},
    {"name": "Bow", "count": 1, "classification": ItemClassification.progression},
    {"name": "Dash", "count": 1, "classification": ItemClassification.progression},
    {"name": "Bash", "count": 1, "classification": ItemClassification.progression},
    {"name": "Grapple", "count": 1, "classification": ItemClassification.progression},
    {"name": "Glide", "count": 1, "classification": ItemClassification.progression},
    {"name": "Flap", "count": 1, "classification": ItemClassification.progression},
    {"name": "Grenade", "count": 1, "classification": ItemClassification.progression},
    {"name": "Flash", "count": 1, "classification": ItemClassification.progression},
    {"name": "WaterDash", "count": 1, "classification": ItemClassification.progression},
    {"name": "Burrow", "count": 1, "classification": ItemClassification.progression},
    {"name": "Launch", "count": 1, "classification": ItemClassification.progression},
    {"name": "Water", "count": 1, "classification": ItemClassification.progression},
    {"name": "Hammer", "count": 1, "classification": ItemClassification.progression},
    {"name": "Sentry", "count": 1, "classification": ItemClassification.progression},
    {"name": "Shuriken", "count": 1, "classification": ItemClassification.progression},
    {"name": "Spear", "count": 1, "classification": ItemClassification.progression},
    {"name": "Blaze", "count": 1, "classification": ItemClassification.progression},
    {"name": "WaterBreath", "count": 1, "classification": ItemClassification.useful},
    {"name": "AncestralLight", "count": 2, "classification": ItemClassification.useful},
    # Collectibles, 125 in total
    {"name": "Health", "count": 24, "classification": ItemClassification.progression_skip_balancing},
    {"name": "Energy", "count": 24, "classification": ItemClassification.progression_skip_balancing},
    {"name": "Keystone", "count": 32, "classification": ItemClassification.progression_skip_balancing},
    {"name": "Ore", "count": 40, "classification": ItemClassification.progression_skip_balancing},
    {"name": "ShardSlot", "count": 5, "classification": ItemClassification.useful},
    # Shards, 31 in total
    {"name": "Overcharge", "count": 1, "classification": ItemClassification.useful},
    {"name": "TripleJump", "count": 1, "classification": ItemClassification.progression},
    {"name": "Wingclip", "count": 1, "classification": ItemClassification.useful},
    {"name": "Bounty", "count": 1, "classification": ItemClassification.useful},
    {"name": "Swap", "count": 1, "classification": ItemClassification.useful},
    {"name": "Magnet", "count": 1, "classification": ItemClassification.useful},
    {"name": "Splinter", "count": 1, "classification": ItemClassification.useful},
    {"name": "Reckless", "count": 1, "classification": ItemClassification.useful},
    {"name": "Quickshot", "count": 1, "classification": ItemClassification.useful},
    {"name": "Resilience", "count": 1, "classification": ItemClassification.useful},
    {"name": "LightHarvest", "count": 1, "classification": ItemClassification.useful},
    {"name": "Vitality", "count": 1, "classification": ItemClassification.useful},
    {"name": "LifeHarvest", "count": 1, "classification": ItemClassification.useful},
    {"name": "EnergyHarvest", "count": 1, "classification": ItemClassification.useful},
    {"name": "EnergyShard", "count": 1, "classification": ItemClassification.useful},
    {"name": "LifePact", "count": 1, "classification": ItemClassification.useful},
    {"name": "LastStand", "count": 1, "classification": ItemClassification.useful},
    {"name": "Sense", "count": 1, "classification": ItemClassification.useful},
    {"name": "UltraBash", "count": 1, "classification": ItemClassification.useful},
    {"name": "UltraGrapple", "count": 1, "classification": ItemClassification.useful},
    {"name": "Overflow", "count": 1, "classification": ItemClassification.useful},
    {"name": "Thorn", "count": 1, "classification": ItemClassification.useful},
    {"name": "Catalyst", "count": 1, "classification": ItemClassification.useful},
    {"name": "Turmoil", "count": 1, "classification": ItemClassification.useful},
    {"name": "Sticky", "count": 1, "classification": ItemClassification.useful},
    {"name": "Finesse", "count": 1, "classification": ItemClassification.useful},
    {"name": "SpiritSurge", "count": 1, "classification": ItemClassification.useful},
    {"name": "Lifeforce", "count": 1, "classification": ItemClassification.useful},
    {"name": "Deflector", "count": 1, "classification": ItemClassification.useful},
    {"name": "Fracture", "count": 1, "classification": ItemClassification.useful},
    {"name": "Arcing", "count": 1, "classification": ItemClassification.useful},
    # TP, 14 in total
    {"name": "BurrowsTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "DenTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "EastPoolsTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "WellspringTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "ReachTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "HollowTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "WestWoodsTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "EastWoodsTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "WestWastesTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "EastWastesTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "OuterRuinsTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "WillowTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "MarshTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "GladesTP", "count": 1, "classification": ItemClassification.progression},
    # Extra TP, 2 in total
    {"name": "WestPoolsTP", "count": 1, "classification": ItemClassification.progression},
    {"name": "InnerRuinsTP", "count": 1, "classification": ItemClassification.progression},
    # Bonus, 15 in total
    {"name": "HealthRegeneration", "count": 3, "classification": ItemClassification.useful},
    {"name": "EnergyRegeneration", "count": 3, "classification": ItemClassification.useful},
    {"name": "ExtraDoubleJump", "count": 1, "classification": ItemClassification.useful},
    {"name": "BlazeEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "SpearEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "ShurikenEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "SentryEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "BowEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "RegenerateEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "FlashEfficiency", "count": 1, "classification": ItemClassification.useful},
    {"name": "GrenadeEfficiency", "count": 1, "classification": ItemClassification.useful},
    # ExtraBonus, 25 in total
    {"name": "RapidSword", "count": 3, "classification": ItemClassification.useful},
    {"name": "RapidHammer", "count": 3, "classification": ItemClassification.useful},
    {"name": "RapidSpear", "count": 2, "classification": ItemClassification.useful},
    {"name": "RapidGrenade", "count": 2, "classification": ItemClassification.useful},
    {"name": "QuickshotUpgrade", "count": 2, "classification": ItemClassification.useful},
    {"name": "RapidRegenerate", "count": 1, "classification": ItemClassification.useful},
    {"name": "MeltingBlaze", "count": 1, "classification": ItemClassification.useful},
    {"name": "MeltingSword", "count": 1, "classification": ItemClassification.useful},
    {"name": "MeltingShuriken", "count": 1, "classification": ItemClassification.useful},
    {"name": "UnchargedBashnades", "count": 1, "classification": ItemClassification.useful},
    {"name": "ExtraGrenade", "count": 1, "classification": ItemClassification.useful},
    {"name": "SplinterGrenade", "count": 1, "classification": ItemClassification.useful},
    {"name": "UnlimitedSentries", "count": 1, "classification": ItemClassification.useful},
    {"name": "SentryBurstUpgrade", "count": 1, "classification": ItemClassification.useful},
    {"name": "SentryFireRate", "count": 1, "classification": ItemClassification.useful},
    {"name": "SplinterShuriken", "count": 2, "classification": ItemClassification.useful},
    {"name": "BashableShuriken", "count": 1, "classification": ItemClassification.useful},
    # Skill upgrades, 6 in total
    {"name": "Jumpgrade", "count": 3, "classification": ItemClassification.useful},
    {"name": "SkillVelocity", "count": 3, "classification": ItemClassification.useful},
    # SpiritLight, complete for 389 locations
    {"name": "SpiritLight", "count": 148, "classification": ItemClassification.filler},
    ]


group_table = {
    "skills": ["Sword", "DoubleJump", "Regenerate", "Bow", "Dash", "Bash", "Grapple", "Glide", "Flap", "Grenade",
               "Flash", "WaterDash", "Burrow", "Launch", "Water", "WaterBreath", "Hammer", "Sentry", "Shuriken",
               "Spear", "Blaze"],
    "collectibles": ["Health", "Energy", "Keystone", "Ore", "ShardSlot", "SpiritLight", "AncestralLight"],
    "shards": ["Overcharge", "TripleJump", "Wingclip", "Bounty", "Swap", "Magnet", "Splinter", "Reckless", "Quickshot",
               "Resilience", "LightHarvest", "Vitality", "LifeHarvest", "EnergyHarvest", "EnergyShard", "LifePact",
               "LastStand", "Sense", "UltraBash", "UltraGrapple", "Overflow", "Thorn", "Catalyst", "Turmoil", "Sticky",
               "Finesse", "SpiritSurge", "Lifeforce", "Deflector", "Fracture", "Arcing"],
    "teleporters": ["MidnightBurrowsTP", "HowlsDenTP", "EastLumaTP", "WellspringTP", "ReachTP", "HollowTP",
                    "WestWoodsTP", "EastWoodsTP", "WestWastesTP", "EastWastesTP", "OuterRuinsTP", "WillowTP",
                    "MarshTP", "GladesTP"],
    "extratp": ["WestLumaTP", "InnerRuinsTP"],
    "bonus": ["HealthRegeneration", "EnergyRegeneration", "ExtraDoubleJump", "ExtraAirDash", "BlazeEfficiency",
              "SpearEfficiency", "ShurikenEfficiency", "SentryEfficiency", "BowEfficiency", "RegenerateEfficiency",
              "FlashEfficiency", "GrenadeEfficiency"],
    "bonus+": ["RapidSword", "RapidHammer", "RapidSpear", "RapidGrenade", "QuickshotUpgrade", "RapidRegenerate",
               "MeltingBlaze", "MeltingSword", "MeltingShuriken", "UnchargedBashnades", "ExtraGrenade",
               "SplinterGrenade", "UnlimitedSentries", "SentryBurstUpgrade", "SentryFireRate", "SplinterShuriken",
               "BashableShuriken"],
    "skillup": ["Jumpgrade", "SkillVelocity"]
    }
